import streamlit as st
from chat import run_startup_chat

st.set_page_config(page_title="Startup Advisor Bot", layout="centered")

st.title("🚀 Startup Advisor Chatbot")
st.markdown("Describe a challenge you're facing as a founder, and get feedback from a multi-agent AI system.")

user_input = st.text_area("What's your current startup issue?", height=200)

if st.button("Analyze and Advise"):
    with st.expander("ℹ️ Disclaimer", expanded=True):
        st.markdown("""
        **Important Notice**  
        The content generated by this application is intended for informational and exploratory purposes only.  
        It is based on user inputs and AI-generated responses, which may not always be accurate, complete, or reliable.  
        Please do **not** implement any suggestions or ideas from this app **without conducting your own research and professional consultation**.  
        The creators of this app are not responsible for any decisions made based on its output.
        """)    
    if user_input.strip():
        with st.spinner("Thinking..."):
            result = run_startup_chat(user_input)
        st.success("Here’s the AI's strategic advice:")
        st.write(result)
    else:
        st.warning("Please enter your startup problem first.")
